export type { SupCategoryGetAllResponse } from './supcategory-get-all.interfaces'
export type { SupCategoryGetOneRequest } from './supcategory-get-one.interfaces'
export type { SupCategoryCreateRequest } from './supcategory-create.interfaces'
export type { SupCategoryUpdateRequest } from './supcategory-update.interfaces'
export type { SupCategoryDeleteRequest } from './supcategory-delete.interfaces'
